apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  db: QnVkZ2V0LUFwcA==
  username: cGlydQ==
  password: cGlydTEyMzQ=
  #rails-master-key: YzBkYTU1NzU0YTAwMjc1NDRiZmI5ZDA1YzI5NDQ1MjA=