apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  db: Budget-App
  username: piru
  password: piru1234
  #rails-master-key: YzBkYTU1NzU0YTAwMjc1NDRiZmI5ZDA1YzI5NDQ1MjA=